# Generated by Django 6.0.3 on 2026-03-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
